# Generated by Django 5.2.4 on 2025-07-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
