# Generated by Django 5.2.4 on 2025-07-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoRede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField()),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "rede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="redes.rede"
                    ),
                ),
            ],
        ),
    ]
