# Generated by Django 5.2.4 on 2025-07-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redes", "0002_eventorede"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intruso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("primeira_deteccao", models.DateTimeField(auto_now_add=True)),
                ("ultima_tentativa", models.DateTimeField(auto_now=True)),
                ("tentativas", models.IntegerField(default=1)),
                ("bloqueado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RegraBloqueio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("limite_tentativas", models.IntegerField(default=3)),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("alert", "Apenas Alertar"),
                            ("block", "Bloquear Automaticamente"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="redes.rede"
                    ),
                ),
            ],
        ),
    ]
