# Generated by Django 5.2.4 on 2025-07-13 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redes", "0003_intruso_regrabloqueio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventorede",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="intruso",
            options={
                "ordering": ["-ultima_tentativa"],
                "verbose_name_plural": "Intrusos",
            },
        ),
        migrations.AlterModelOptions(
            name="regrabloqueio",
            options={
                "verbose_name": "Regra de Bloqueio",
                "verbose_name_plural": "Regras de Bloqueio",
            },
        ),
        migrations.RenameField(
            model_name="eventorede",
            old_name="data_hora",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="rede",
            name="descricao",
        ),
        migrations.AddField(
            model_name="eventorede",
            name="latencia",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventorede",
            name="portas_abertas",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="intruso",
            name="mac_address",
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name="intruso",
            name="motivo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rede",
            name="dispositivos_autorizados",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="rede",
            name="gateway",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rede",
            name="intervalo_verificacao",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="rede",
            name="mascara",
            field=models.CharField(default="255.255.255.0", max_length=15),
        ),
        migrations.AddField(
            model_name="regrabloqueio",
            name="criada_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regrabloqueio",
            name="ip",
            field=models.GenericIPAddressField(default="127.0.0.1"),
        ),
        migrations.AddField(
            model_name="regrabloqueio",
            name="motivo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="regrabloqueio",
            name="porta",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="regrabloqueio",
            name="protocolo",
            field=models.CharField(
                choices=[("TCP", "TCP"), ("UDP", "UDP")], default="TCP", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="intruso",
            name="tentativas",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="regrabloqueio",
            name="acao",
            field=models.CharField(
                choices=[("alert", "Alerta"), ("block", "Bloquear")],
                default="alert",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="regrabloqueio",
            name="limite_tentativas",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddIndex(
            model_name="eventorede",
            index=models.Index(
                fields=["-timestamp"], name="redes_event_timesta_619c4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventorede",
            index=models.Index(
                fields=["rede", "status"], name="redes_event_rede_id_8338d5_idx"
            ),
        ),
    ]
